package domain

// Article represents a collected news article.
type Article struct {
	ID            int64
	SourceID      int64
	PipelineRunID *int64
	BroadcastID   *int64
	Title         string
	URL           string
	ThumbnailURL  *string // local serving path e.g. "/thumbnails/42.jpg", nil if unavailable
	RawContent    *string // nullified after retention period for DB size reduction
	Category      string
	IsSelected    bool
	SelectRank    *int    // 1 = highest relevance; nil = not selected
	Summary       *string // DJ narration text generated by Gemini
	CreatedAt     string
	ProcessedAt   *string
}
