package domain

// ReservedCategories are category names that must not be created by users.
// "stop"   conflicts with POST /api/play/stop routing.
// "digest" is auto-generated by the pipeline and must remain system-owned.
var ReservedCategories = map[string]bool{
	"stop":   true,
	"digest": true,
}

// CategorySettings holds per-category pipeline and TTS configuration.
type CategorySettings struct {
	Category               string
	DisplayName            string
	ArticlesPerEpisode     int
	SummaryCharsPerArticle int
	Language               string // "ja" or "en"
	TTSEngine              string // "voicevox" or "edge-tts"
	VoicevoxSpeakerID      int    // VOICEVOX style_id (used when TTSEngine == "voicevox")
	TTSVoice               *string // edge-tts voice name (used when TTSEngine == "edge-tts")
	Enabled                bool
	SortOrder              int
	CreatedAt              string
}
