package domain

// ReservedCategories are category names that must not be created by users.
// "stop"   conflicts with POST /api/play/stop routing.
// "digest" is auto-generated by the pipeline and must remain system-owned.
var ReservedCategories = map[string]bool{
	"stop":   true,
	"digest": true,
}

// CategorySettings holds per-category pipeline and TTS configuration.
type CategorySettings struct {
	Category               string
	DisplayName            string
	ArticlesPerEpisode     int
	SummaryCharsPerArticle int
	Language               string  // "ja" or "en"
	TTSEngine              string  // "voicevox", "edge-tts", or "gcloud"
	VoicevoxSpeakerID      int     // VOICEVOX style_id (used when TTSEngine == "voicevox")
	TTSVoice               *string // Cloud TTS / edge-tts voice name
	SpeedScale             float64 // TTS speaking rate (0.25–4.0); default 1.0
	Enabled                bool
	SortOrder              int
	CreatedAt              string
}
